# Generated by Django 4.1.7 on 2023-07-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_cust', models.CharField(max_length=50)),
                ('alamat_cust', models.TextField()),
                ('no_hp_cust', models.CharField(max_length=20)),
                ('flag_cust', models.CharField(max_length=10)),
            ],
        ),
    ]
