# Generated by Django 4.1.7 on 2023-07-31 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_branch', models.CharField(max_length=20)),
                ('nama_agen', models.CharField(max_length=20)),
                ('alamat_branch', models.TextField(max_length=100)),
                ('alamat_singkat_branch', models.CharField(max_length=20)),
                ('no_telp_branch', models.CharField(max_length=20)),
                ('flag_branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Harga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asal', models.CharField(max_length=15)),
                ('tujuan_kec', models.CharField(max_length=20)),
                ('tujuan_coveran', models.CharField(max_length=20)),
                ('price_kg', models.IntegerField()),
                ('price_granmax', models.IntegerField()),
                ('price_engkel', models.IntegerField()),
                ('price_cdd', models.IntegerField()),
                ('price_fuso', models.IntegerField()),
                ('price_wing', models.IntegerField()),
                ('price_towing', models.IntegerField()),
                ('price_udara', models.IntegerField()),
                ('estimasi_darat', models.IntegerField()),
                ('estimasi_udara', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_karyawan', models.CharField(max_length=50)),
                ('jabatan', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('alamat_karyawan', models.TextField()),
                ('no_hp_karyawan', models.CharField(max_length=15)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistik.branch')),
            ],
        ),
    ]
