# Generated by Django 4.1.7 on 2023-08-11 03:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0002_alter_karyawan_slug_karyawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='slug_karyawan',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='id_karyawan'),
        ),
    ]
