# Generated by Django 4.1.7 on 2023-07-31 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0002_branch_harga_karyawan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='flag_branch',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='nama_agen',
        ),
        migrations.CreateModel(
            name='Agen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_agen', models.CharField(max_length=20)),
                ('alamat_agen', models.TextField(max_length=100)),
                ('alamat_singkat_agen', models.CharField(max_length=20)),
                ('no_telp_agen', models.CharField(max_length=20)),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistik.branch')),
            ],
        ),
    ]
