# Generated by Django 4.1.7 on 2023-08-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0003_alter_karyawan_slug_karyawan'),
    ]

    operations = [
        migrations.AddField(
            model_name='harga',
            name='price_bl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
