# Generated by Django 4.1.7 on 2023-08-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0004_harga_price_bl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='id_karyawan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
