# Generated by Django 4.1.7 on 2023-08-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0004_karyawan_agen_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agen',
            name='id_agen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='id_branch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='id_karyawan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
