# Generated by Django 4.1.7 on 2023-08-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0005_agen_id_agen_branch_id_branch_karyawan_id_karyawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='id_karyawan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
