# Generated by Django 4.1.7 on 2023-08-17 01:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0005_alter_karyawan_id_karyawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alamat_cust',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='flag_cust',
            field=models.CharField(choices=[('ret', 'Retail'), ('comp', 'Company')], default='ret', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nama_cust',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='no_hp_cust',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('do_po', models.CharField(max_length=50, null=True)),
                ('no_resi', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_pengirim', models.CharField(max_length=20)),
                ('alamat_pengirim', models.CharField(max_length=50)),
                ('no_hp_penerima', models.CharField(max_length=15)),
                ('nama_penerima', models.CharField(max_length=20)),
                ('alamat_penerima', models.CharField(max_length=50)),
                ('layanan', models.CharField(choices=[('darat', 'darat'), ('laut', 'laut'), ('udara', 'udara'), ('towing', 'towing'), ('trucking', 'trucking'), ('city', 'city')], default='darat', max_length=10)),
                ('asal', models.CharField(max_length=20)),
                ('tujuan', models.CharField(max_length=20)),
                ('tujuan_coveran', models.CharField(max_length=20)),
                ('harga_id', models.IntegerField(default=0)),
                ('berat', models.IntegerField(default=0)),
                ('diskon', models.IntegerField(default=0)),
                ('biaya_surat', models.IntegerField(default=0)),
                ('biaya_packing', models.IntegerField(default=0)),
                ('jenis_barang', models.CharField(max_length=20)),
                ('taksasi', models.IntegerField(default=0)),
                ('premi_asuransi', models.IntegerField(default=0)),
                ('total_cash', models.IntegerField(default=0)),
                ('total_bayartujuan', models.IntegerField(default=0)),
                ('total_transaksi', models.IntegerField(default=0)),
                ('status_trx', models.CharField(default='1', max_length=25)),
                ('no_manivest', models.CharField(max_length=25, null=True)),
                ('slug_transkasi', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='no_transaksi')),
                ('id_agen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistik.agen')),
                ('id_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistik.branch')),
                ('karyawan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistik.karyawan')),
                ('no_hp_pengirim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistik.customer')),
            ],
        ),
    ]
