# Generated by Django 4.1.7 on 2023-08-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0006_alter_customer_alamat_cust_alter_customer_flag_cust_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp_penerima', models.CharField(max_length=15)),
                ('nama_penerima', models.CharField(max_length=30)),
                ('alamat_penerima', models.CharField(max_length=50)),
            ],
        ),
    ]
