# Generated by Django 4.1.7 on 2023-08-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0006_alter_karyawan_id_karyawan'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slug_branch',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
