# Generated by Django 4.1.7 on 2023-08-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0007_branch_slug_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='alamat_singkat_branch',
            new_name='kota',
        ),
    ]
