# Generated by Django 4.1.7 on 2023-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistik', '0008_rename_alamat_singkat_branch_branch_kota'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='kota_karyawan',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='slug_karyawan',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
